project:
  type: website

website:
  title: "Health AI in R Workshop"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  eval: false
engine: knitr

