project:
  type: website

website:
  title: "Health AI in R Workshop"
  site-url: https://brookewolford.com/HealthAIinR
  repo-url: https://github.com/bnwolford/HealthAIinR
  repo-actions: [edit, issue]
  navbar:
    left:
      - href: index.qmd
        text: Home
      - icon: github
        href: https://github.com/bnwolford/HealthAIinR
        aria-label: GitHub repository
  sidebar:
    contents:
      - section: "Lesson Modules"
        contents: "modules/*"
      - section: Activities
        contents: "activities/*"
      - section: Bonus
        contents: "bonus/*"
  page-footer:
    center:
      - LICENSE.md

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  eval: false
  echo: true
  freeze: auto
engine: knitr

